name: Frontend CI

on:
  pull_request:
    branches:
      - main
    paths:
      - "frontend/**"
  push:
    branches:
      - main
    paths:
      - "frontend/**"

jobs:
  pipeline:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the frontend folder
        uses: actions/checkout@v4
        with:
          sparse-checkout: frontend
      - name: check
        run: ls -a
