name: Frontend CI

on:
  pull_request:
    branches: [main]
    paths: ["frontend/**"]
  push:
    paths: ["frontend/**"]

jobs:
  pipeline:
    runs-on: ubuntu-latest
    steps:
      - name: Code checkout
        uses: actions/checkout@v4
        with:
          path: frontend
      - name: Set up node
        uses: actions/setup-node@v4
        with:
          node-version: "20"
      - name: Install dependencies
        run: |
          cd frontend
          npm i
      - name: Style check
        run: |
          cd frontend
          npm run lint
      - name: Build the app
        run: |
          cd frontend
          npm run build
